version: '3.3'
services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MG_PASSWORD}
    volumes:
      - mg_data:/data
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 30s
    networks:
      - mpj-net
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 9001:9001
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shlink -d shlink-db"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 30s
    networks:
      - mpj-net
    restart: on-failure

  jupyterlab:
    container_name: jupyterlab
    image: cristiancantoro/jupyterlab:latest
    volumes:
      - jupyterlab_data:/home/jovyan/work
    ports:
      - 8888:8888
    networks:
      - mpj-net
    depends_on:
      - postgres
      - mongo
    links:
      - postgres
      - mongo

networks:
  mpj-net:

volumes:
  mg_data:
  pg_data:
  jupyterlab_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/jupyterlab
